/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AITranslatorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// node_modules/google-translate-api-browser/dest/browser/esm.js
var a = { d: (e2, n2) => {
  for (var r2 in n2)
    a.o(n2, r2) && !a.o(e2, r2) && Object.defineProperty(e2, r2, { enumerable: true, get: n2[r2] });
}, o: (a2, e2) => Object.prototype.hasOwnProperty.call(a2, e2) };
var e = {};
a.d(e, { Ce: () => c, ZP: () => d, j1: () => r, Eb: () => o, e6: () => i, Iu: () => h });
var n = { from: "auto", to: "en", hl: "en", tld: "com", rpcids: "MkEWBc" };
function r(a2) {
  var e2 = void 0 === a2 ? {} : a2, r2 = e2.rpcids, t2 = void 0 === r2 ? n.rpcids : r2, o2 = e2.hl, i2 = void 0 === o2 ? n.hl : o2, c2 = e2.tld, s2 = void 0 === c2 ? n.tld : c2;
  if (!function(a3) {
    return Boolean(a3.match(/^[a-zA-Z]{2,63}$/));
  }(s2))
    throw new Error("Invalid TLD: Must be 2-63 letters only");
  var u2 = new URLSearchParams({ rpcids: t2, "source-path": "/", hl: i2, "soc-app": "1", "soc-platform": "1", "soc-device": "1" });
  return "https://translate.google.".concat(s2, "/_/TranslateWebserverUi/data/batchexecute?").concat(u2);
}
var t = { auto: "Automatic", af: "Afrikaans", sq: "Albanian", am: "Amharic", ar: "Arabic", hy: "Armenian", az: "Azerbaijani", eu: "Basque", be: "Belarusian", bn: "Bengali", bs: "Bosnian", bg: "Bulgarian", ca: "Catalan", ceb: "Cebuano", ny: "Chichewa", zh: "Chinese Simplified", "zh-cn": "Chinese Simplified", "zh-tw": "Chinese Traditional", co: "Corsican", hr: "Croatian", cs: "Czech", da: "Danish", nl: "Dutch", en: "English", "en-US": "English", eo: "Esperanto", et: "Estonian", tl: "Filipino", fi: "Finnish", fr: "French", fy: "Frisian", gl: "Galician", ka: "Georgian", de: "German", el: "Greek", gu: "Gujarati", ht: "Haitian Creole", ha: "Hausa", haw: "Hawaiian", he: "Hebrew", iw: "Hebrew", hi: "Hindi", hmn: "Hmong", hu: "Hungarian", is: "Icelandic", ig: "Igbo", id: "Indonesian", ga: "Irish", it: "Italian", ja: "Japanese", jw: "Javanese", kn: "Kannada", kk: "Kazakh", km: "Khmer", rw: "Kinyarwanda", ko: "Korean", ku: "Kurdish (Kurmanji)", ky: "Kyrgyz", lo: "Lao", la: "Latin", lv: "Latvian", lt: "Lithuanian", lb: "Luxembourgish", mk: "Macedonian", mg: "Malagasy", ms: "Malay", ml: "Malayalam", mt: "Maltese", mi: "Maori", mr: "Marathi", mn: "Mongolian", my: "Myanmar (Burmese)", ne: "Nepali", no: "Norwegian", or: "Odia (Oriya)", ps: "Pashto", fa: "Persian", pl: "Polish", pt: "Portuguese", pa: "Punjabi", ro: "Romanian", ru: "Russian", sm: "Samoan", gd: "Scots Gaelic", sr: "Serbian", st: "Sesotho", sn: "Shona", sd: "Sindhi", si: "Sinhala", sk: "Slovak", sl: "Slovenian", so: "Somali", es: "Spanish", su: "Sundanese", sw: "Swahili", sv: "Swedish", tg: "Tajik", ta: "Tamil", tt: "Tatar", te: "Telugu", th: "Thai", tr: "Turkish", tk: "Turkmen", uk: "Ukrainian", ur: "Urdu", ug: "Uyghur", uz: "Uzbek", vi: "Vietnamese", cy: "Welsh", xh: "Xhosa", yi: "Yiddish", yo: "Yoruba", zu: "Zulu" };
var o = function(a2) {
  return Boolean(t[a2]);
};
function i(a2, e2) {
  void 0 === e2 && (e2 = false);
  var n2 = function(a3) {
    try {
      var e3 = JSON.parse(a3.replace(/^\)]}'/, ""));
      return JSON.parse(e3[0][2]);
    } catch (a4) {
      throw new Error("Data is either empty or corrupted");
    }
  }(a2), r2 = { text: n2[1][0][0][5].reduce(function(a3, e3) {
    var n3 = e3[0];
    return a3 ? "".concat(a3, " ").concat(n3) : n3;
  }, ""), pronunciation: n2[1][0][0][1], from: { language: { didYouMean: Boolean(n2[0][1]), iso: n2[2] }, text: { pronunciation: n2[0][0], autoCorrected: Boolean(n2[0][1]), value: n2[0][6][0], didYouMean: n2[0][1] ? n2[0][1][0][4] : null } } };
  return e2 && (r2.raw = n2), r2;
}
function c(a2, e2) {
  var r2 = void 0 === e2 ? {} : e2, t2 = r2.rpcids, o2 = void 0 === t2 ? n.rpcids : t2, i2 = r2.from, c2 = void 0 === i2 ? n.from : i2, s2 = r2.to, u2 = void 0 === s2 ? n.to : s2, l2 = a2.trim().replace(/["]/g, "\\\\\\$&").replace(/\r\n|\r|\n/g, "\\\\n"), h2 = encodeURIComponent('[[["'.concat(o2, '","[[\\"').concat(l2, '\\",\\"').concat(c2, '\\",\\"').concat(u2, '\\",1],[]]",null,"generic"]]]'));
  return "f.req=".concat(h2, "&");
}
var s = function() {
  return s = Object.assign || function(a2) {
    for (var e2, n2 = 1, r2 = arguments.length; n2 < r2; n2++)
      for (var t2 in e2 = arguments[n2])
        Object.prototype.hasOwnProperty.call(e2, t2) && (a2[t2] = e2[t2]);
    return a2;
  }, s.apply(this, arguments);
};
var u = function(a2, e2, n2, r2) {
  return new (n2 || (n2 = Promise))(function(t2, o2) {
    function i2(a3) {
      try {
        s2(r2.next(a3));
      } catch (a4) {
        o2(a4);
      }
    }
    function c2(a3) {
      try {
        s2(r2.throw(a3));
      } catch (a4) {
        o2(a4);
      }
    }
    function s2(a3) {
      var e3;
      a3.done ? t2(a3.value) : (e3 = a3.value, e3 instanceof n2 ? e3 : new n2(function(a4) {
        a4(e3);
      })).then(i2, c2);
    }
    s2((r2 = r2.apply(a2, e2 || [])).next());
  });
};
var l = function(a2, e2) {
  var n2, r2, t2, o2, i2 = { label: 0, sent: function() {
    if (1 & t2[0])
      throw t2[1];
    return t2[1];
  }, trys: [], ops: [] };
  return o2 = { next: c2(0), throw: c2(1), return: c2(2) }, "function" == typeof Symbol && (o2[Symbol.iterator] = function() {
    return this;
  }), o2;
  function c2(c3) {
    return function(s2) {
      return function(c4) {
        if (n2)
          throw new TypeError("Generator is already executing.");
        for (; o2 && (o2 = 0, c4[0] && (i2 = 0)), i2; )
          try {
            if (n2 = 1, r2 && (t2 = 2 & c4[0] ? r2.return : c4[0] ? r2.throw || ((t2 = r2.return) && t2.call(r2), 0) : r2.next) && !(t2 = t2.call(r2, c4[1])).done)
              return t2;
            switch (r2 = 0, t2 && (c4 = [2 & c4[0], t2.value]), c4[0]) {
              case 0:
              case 1:
                t2 = c4;
                break;
              case 4:
                return i2.label++, { value: c4[1], done: false };
              case 5:
                i2.label++, r2 = c4[1], c4 = [0];
                continue;
              case 7:
                c4 = i2.ops.pop(), i2.trys.pop();
                continue;
              default:
                if (!((t2 = (t2 = i2.trys).length > 0 && t2[t2.length - 1]) || 6 !== c4[0] && 2 !== c4[0])) {
                  i2 = 0;
                  continue;
                }
                if (3 === c4[0] && (!t2 || c4[1] > t2[0] && c4[1] < t2[3])) {
                  i2.label = c4[1];
                  break;
                }
                if (6 === c4[0] && i2.label < t2[1]) {
                  i2.label = t2[1], t2 = c4;
                  break;
                }
                if (t2 && i2.label < t2[2]) {
                  i2.label = t2[2], i2.ops.push(c4);
                  break;
                }
                t2[2] && i2.ops.pop(), i2.trys.pop();
                continue;
            }
            c4 = e2.call(a2, i2);
          } catch (a3) {
            c4 = [6, a3], r2 = 0;
          } finally {
            n2 = t2 = 0;
          }
        if (5 & c4[0])
          throw c4[1];
        return { value: c4[0] ? c4[1] : void 0, done: true };
      }([c3, s2]);
    };
  }
};
function h(a2, e2) {
  return void 0 === e2 && (e2 = {}), u(this, void 0, void 0, function() {
    var t2, o2, u2, h2, d2;
    return l(this, function(l2) {
      switch (l2.label) {
        case 0:
          return t2 = s(s({ raw: false, corsUrl: "" }, n), e2), o2 = c(a2, t2), u2 = r(t2), [4, fetch("".concat(e2.corsUrl).concat(u2), { method: "POST", headers: s({ "Content-Type": "application/x-www-form-urlencoded" }, t2.headers), body: o2 })];
        case 1:
          if (!(h2 = l2.sent()).ok)
            throw new Error("Request failed");
          return d2 = i, [4, h2.text()];
        case 2:
          return [2, d2.apply(void 0, [l2.sent(), t2.raw])];
      }
    });
  });
}
var d = h;
var p = e.Ce;
var f = e.ZP;
var m = e.j1;
var v = e.Eb;
var b = e.e6;
var y = e.Iu;

// main.ts
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
var DEFAULT_SETTINGS = {
  provider: "gemini",
  geminiApiKey: "",
  openaiApiKey: "",
  openRouterApiKey: "",
  geminiModel: "gemini-1.5-pro",
  openaiModel: "gpt-4o",
  openRouterModel: "meta-llama/llama-3-8b-instruct",
  targetLanguage: "Vietnamese",
  triggerMode: "auto",
  providerPrompts: {
    "gemini": "Analyze the following text. If it is a single word or short phrase, provide its definition, a list of synonyms, and some aliases. If it is a longer text/paragraph, provide a direct translation and a brief explanation. Respond entirely in {{targetLanguage}}. Format the response in concise Markdown. At the VERY end of your response, include a line: 'Aliases: [comma separated aliases]'.\n\nText: {{text}}",
    "openai": "Analyze the following text. If it is a single word or short phrase, provide its definition, a list of synonyms, and some aliases. If it is a longer text/paragraph, provide a direct translation and a brief explanation. Respond entirely in {{targetLanguage}}. Format the response in concise Markdown. At the VERY end of your response, include a line: 'Aliases: [comma separated aliases]'.\n\nText: {{text}}",
    "openrouter": "Analyze the following text. If it is a single word or short phrase, provide its definition, a list of synonyms, and some aliases. If it is a longer text/paragraph, provide a direct translation and a brief explanation. Respond entirely in {{targetLanguage}}. Format the response in concise Markdown. At the VERY end of your response, include a line: 'Aliases: [comma separated aliases]'.\n\nText: {{text}}",
    "google": "Translate: {{text}}",
    "free-dictionary": "Dictionary lookup: {{text}}"
  },
  providerSaveTemplates: {
    "gemini": "---\naliases: [{{aliases}}]\n---\n# {{word}}\n\n{{definition}}\n\n*Saved on: {{date}} {{time}}*",
    "openai": "---\naliases: [{{aliases}}]\n---\n# {{word}}\n\n{{definition}}\n\n*Saved on: {{date}} {{time}}*",
    "openrouter": "---\naliases: [{{aliases}}]\n---\n# {{word}}\n\n{{definition}}\n\n*Saved on: {{date}} {{time}}*",
    "google": "---\naliases: [{{word}}]\n---\n# {{word}}\n\n{{definition}}\n\n*Saved on: {{date}} {{time}}*",
    "free-dictionary": "---\naliases: [{{aliases}}]\n---\n# {{word}}\n\n{{definition}}\n\n*Saved on: {{date}} {{time}}*"
  },
  saveFolder: "AI-Definitions",
  useSharedTemplate: false,
  sharedSaveTemplate: "---\naliases: [{{aliases}}]\n---\n# {{word}}\n\n{{definition}}\n\n*Saved on: {{date}} {{time}}*",
  providerLoop: ["gemini", "openai", "openrouter", "google", "free-dictionary"]
};
var AITranslatorPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    __publicField(this, "settings");
    __publicField(this, "refreshActivePopup", null);
    __publicField(this, "selectionTimeout", null);
    __publicField(this, "popupEl", null);
    __publicField(this, "activeHandlers", {});
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "translate-selected-text-replace",
      name: "Translate Selected Text (Replace)",
      editorCallback: async (editor, view) => {
        const selectedText = editor.getSelection();
        if (!selectedText) {
          new import_obsidian.Notice("Please select a word or phrase to translate.");
          return;
        }
        new import_obsidian.Notice(`Translating using ${this.settings.provider}...`);
        try {
          const translation = await this.translateText(selectedText);
          if (translation) {
            editor.replaceSelection(translation);
            new import_obsidian.Notice("Translation complete.");
          } else {
            new import_obsidian.Notice("Failed to get translation.");
          }
        } catch (error) {
          console.error("Translation error:", error);
          new import_obsidian.Notice(`Translation error: ${error.message || error}`);
        }
      }
    });
    this.addCommand({
      id: "translate-selected-text-append",
      name: "Translate Selected Text (Append in parentheses)",
      editorCallback: async (editor, view) => {
        const selectedText = editor.getSelection();
        if (!selectedText) {
          new import_obsidian.Notice("Please select a word or phrase to translate.");
          return;
        }
        new import_obsidian.Notice(`Translating using ${this.settings.provider}...`);
        try {
          const translation = await this.translateText(selectedText);
          if (translation) {
            editor.replaceSelection(`${selectedText} (${translation})`);
            new import_obsidian.Notice("Translation complete.");
          } else {
            new import_obsidian.Notice("Failed to get translation.");
          }
        } catch (error) {
          console.error("Translation error:", error);
          new import_obsidian.Notice(`Translation error: ${error.message || error}`);
        }
      }
    });
    this.addCommand({
      id: "show-dictionary-popup",
      name: "Show Dictionary Popup for Selection",
      editorCallback: async (editor, view) => {
        const selectedText = editor.getSelection();
        if (!selectedText) {
          new import_obsidian.Notice("Please select text first.");
          return;
        }
        if (this.settings.triggerMode !== "disabled") {
          const cmView = view.editor.cm;
          if (cmView) {
            await this.showPopup(selectedText, cmView);
          }
        }
      }
    });
    this.addSettingTab(new AITranslatorSettingTab(this.app, this));
    this.addCommand({
      id: "cycle-ai-provider",
      name: "Cycle AI Provider",
      callback: async () => {
        const allProviders = ["gemini", "openai", "openrouter", "google", "free-dictionary"];
        const loop = this.settings.providerLoop && this.settings.providerLoop.length > 0 ? this.settings.providerLoop : allProviders;
        let currentIndex = loop.indexOf(this.settings.provider);
        let nextIndex = (currentIndex + 1) % loop.length;
        this.settings.provider = loop[nextIndex];
        await this.saveSettings();
        new import_obsidian.Notice(`Provider switched to: ${this.settings.provider}`);
        if (this.refreshActivePopup) {
          await this.refreshActivePopup(this.settings.provider);
        }
      }
    });
    this.registerEditorExtension(this.getEditorExtension());
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async translateText(text) {
    const promptTemplate = this.settings.providerPrompts[this.settings.provider] || DEFAULT_SETTINGS.providerPrompts[this.settings.provider];
    const prompt = promptTemplate.replace("{{targetLanguage}}", this.settings.targetLanguage).replace("{{text}}", text);
    switch (this.settings.provider) {
      case "gemini":
        return await this.callGemini(prompt);
      case "openai":
        return await this.callOpenAI(prompt);
      case "openrouter":
        return await this.callOpenRouter(prompt);
      case "google":
        return await this.callGoogleTranslate(text);
      case "free-dictionary":
        return await this.callFreeDictionary(text);
      default:
        throw new Error("Invalid provider");
    }
  }
  async callFreeDictionary(text) {
    try {
      const url = `https://api.dictionaryapi.dev/api/v2/entries/en/${encodeURIComponent(text.trim())}`;
      const response = await (0, import_obsidian.requestUrl)({ url });
      if (response.status === 404) {
        return "No definition found.";
      }
      if (response.status !== 200) {
        throw new Error(`Free Dictionary API Error ${response.status}: ${response.text}`);
      }
      const data = response.json;
      if (!data || data.length === 0)
        return "No definition found.";
      let result = `# ${data[0].word}

`;
      const aliases = [];
      data[0].meanings.forEach((meaning) => {
        result += `### ${meaning.partOfSpeech}
`;
        meaning.definitions.forEach((def, idx) => {
          result += `${idx + 1}. ${def.definition}
`;
          if (def.example)
            result += `   *Example: ${def.example}*
`;
        });
        if (meaning.synonyms && meaning.synonyms.length > 0) {
          result += `
**Synonyms:** ${meaning.synonyms.join(", ")}
`;
          aliases.push(...meaning.synonyms);
        }
        result += "\n";
      });
      if (aliases.length > 0) {
        result += `Aliases: ${aliases.slice(0, 5).join(", ")}`;
      } else {
        result += `Aliases: ${data[0].word}`;
      }
      return result;
    } catch (error) {
      console.error("Free Dictionary error:", error);
      throw new Error(`Free Dictionary error: ${error.message || error}`);
    }
  }
  async callGoogleTranslate(text) {
    try {
      const targetLang = this.getLanguageCode(this.settings.targetLanguage);
      const url = m({ hl: targetLang });
      const body = p(text, { from: "auto", to: targetLang });
      const response = await (0, import_obsidian.requestUrl)({
        url,
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8"
        },
        body
      });
      if (response.status !== 200) {
        throw new Error(`Google Translate API Error ${response.status}: ${response.text}`);
      }
      const result = b(response.text);
      return result.text;
    } catch (error) {
      console.error("Google Translate error:", error);
      throw new Error(`Google Translate error: ${error.message || error}`);
    }
  }
  getLanguageCode(language) {
    const langMap = {
      "Vietnamese": "vi",
      "English": "en",
      "French": "fr",
      "German": "de",
      "Spanish": "es",
      "Japanese": "ja",
      "Korean": "ko",
      "Chinese": "zh-CN",
      "Russian": "ru",
      "Italian": "it",
      "Portuguese": "pt"
    };
    if (language.length === 2)
      return language.toLowerCase();
    return langMap[language] || "en";
  }
  async callGemini(prompt) {
    if (!this.settings.geminiApiKey) {
      throw new Error("Gemini API Key is missing. Please add it in settings.");
    }
    const model = this.settings.geminiModel || "gemini-1.5-pro";
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${this.settings.geminiApiKey}`;
    const body = {
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: {
        temperature: 0.1
      }
    };
    const response = await (0, import_obsidian.requestUrl)({
      url,
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(body)
    });
    if (response.status !== 200) {
      throw new Error(`API Error ${response.status}: ${response.text}`);
    }
    const data = response.json;
    if (!data.candidates || data.candidates.length === 0) {
      throw new Error("No translation returned from Gemini.");
    }
    return data.candidates[0].content.parts[0].text.trim();
  }
  async callOpenAI(prompt) {
    if (!this.settings.openaiApiKey) {
      throw new Error("OpenAI API Key is missing. Please add it in settings.");
    }
    const url = "https://api.openai.com/v1/chat/completions";
    const body = {
      model: this.settings.openaiModel || "gpt-4o",
      messages: [{ role: "user", content: prompt }],
      temperature: 0.1
    };
    const response = await (0, import_obsidian.requestUrl)({
      url,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.settings.openaiApiKey}`
      },
      body: JSON.stringify(body)
    });
    if (response.status !== 200) {
      throw new Error(`API Error ${response.status}: ${response.text}`);
    }
    const data = response.json;
    if (!data.choices || data.choices.length === 0) {
      throw new Error("No translation returned from OpenAI.");
    }
    return data.choices[0].message.content.trim();
  }
  async callOpenRouter(prompt) {
    if (!this.settings.openRouterApiKey) {
      throw new Error("OpenRouter API Key is missing. Please add it in settings.");
    }
    const url = "https://openrouter.ai/api/v1/chat/completions";
    const body = {
      model: this.settings.openRouterModel || "meta-llama/llama-3-8b-instruct",
      messages: [{ role: "user", content: prompt }],
      temperature: 0.1
    };
    const response = await (0, import_obsidian.requestUrl)({
      url,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.settings.openRouterApiKey}`,
        "HTTP-Referer": "https://github.com/obsidianmd/obsidian-api",
        // Required by OpenRouter
        "X-Title": "Obsidian AI Translator"
        // Optional but recommended by OpenRouter
      },
      body: JSON.stringify(body)
    });
    if (response.status !== 200) {
      throw new Error(`API Error ${response.status}: ${response.text}`);
    }
    const data = response.json;
    if (!data.choices || data.choices.length === 0) {
      throw new Error("No translation returned from OpenRouter.");
    }
    return data.choices[0].message.content.trim();
  }
  getEditorExtension() {
    return import_state.Prec.lowest(import_view.EditorView.updateListener.of((update) => {
      if (update.selectionSet) {
        const selection = update.state.selection.main;
        if (!selection.empty) {
          if (this.settings.triggerMode === "auto") {
            const text = update.state.doc.sliceString(selection.from, selection.to).trim();
            if (text.length > 0) {
              this.handleSelection(text, update.view);
            }
          }
        } else {
          this.removePopup();
        }
      }
    }));
  }
  handleSelection(text, view) {
    if (this.selectionTimeout)
      clearTimeout(this.selectionTimeout);
    this.removePopup();
    this.selectionTimeout = setTimeout(async () => {
      await this.showPopup(text, view);
    }, 700);
  }
  removePopup() {
    const existingPopups = document.querySelectorAll(".ai-translator-popup");
    existingPopups.forEach((el) => el.remove());
    this.popupEl = null;
    if (this.activeHandlers.escape)
      document.removeEventListener("keydown", this.activeHandlers.escape);
    if (this.activeHandlers.clickOutside)
      document.removeEventListener("mousedown", this.activeHandlers.clickOutside);
    if (this.activeHandlers.mousemove)
      document.removeEventListener("mousemove", this.activeHandlers.mousemove);
    if (this.activeHandlers.touchmove)
      document.removeEventListener("touchmove", this.activeHandlers.touchmove);
    if (this.activeHandlers.mouseup)
      document.removeEventListener("mouseup", this.activeHandlers.mouseup);
    if (this.activeHandlers.touchend)
      document.removeEventListener("touchend", this.activeHandlers.touchend);
    this.activeHandlers = {};
    this.refreshActivePopup = null;
  }
  async showPopup(text, view) {
    const selection = view.state.selection.main;
    const domRect = view.coordsAtPos(selection.to);
    if (!domRect)
      return;
    this.popupEl = document.body.createEl("div", { cls: "ai-translator-popup" });
    if (import_obsidian.Platform.isMobile) {
      this.popupEl.style.left = "50%";
      this.popupEl.style.top = "20%";
      this.popupEl.style.transform = "translateX(-50%)";
    } else {
      this.popupEl.style.left = `${domRect.left}px`;
      this.popupEl.style.top = `${domRect.bottom + 10}px`;
    }
    const header = this.popupEl.createEl("div", { cls: "ai-translator-popup-header" });
    header.createEl("span", { text: "AI Dictionary", cls: "ai-translator-popup-title" });
    const closeBtn = header.createEl("div", { cls: "ai-translator-popup-close-btn" });
    (0, import_obsidian.setIcon)(closeBtn, "x");
    (0, import_obsidian.setTooltip)(closeBtn, "Close");
    closeBtn.onclick = (e2) => {
      e2.stopPropagation();
      this.removePopup();
    };
    let isDragging = false;
    let startX, startY;
    let initialLeft, initialTop;
    const startDragging = (clientX, clientY) => {
      isDragging = true;
      startX = clientX;
      startY = clientY;
      const rect = this.popupEl.getBoundingClientRect();
      initialLeft = rect.left;
      initialTop = rect.top;
      if (this.popupEl.style.transform) {
        this.popupEl.style.transform = "";
        this.popupEl.style.left = `${initialLeft}px`;
        this.popupEl.style.top = `${initialTop}px`;
      }
      header.style.cursor = "grabbing";
    };
    header.onmousedown = (e2) => {
      startDragging(e2.clientX, e2.clientY);
    };
    header.ontouchstart = (e2) => {
      if (e2.touches.length > 0) {
        startDragging(e2.touches[0].clientX, e2.touches[0].clientY);
      }
    };
    const moveHandler = (clientX, clientY) => {
      if (!isDragging || !this.popupEl)
        return;
      const dx = clientX - startX;
      const dy = clientY - startY;
      let newLeft = initialLeft + dx;
      let newTop = initialTop + dy;
      const rect = this.popupEl.getBoundingClientRect();
      const padding = 10;
      newLeft = Math.max(padding, Math.min(newLeft, window.innerWidth - rect.width - padding));
      newTop = Math.max(padding, Math.min(newTop, window.innerHeight - rect.height - padding));
      this.popupEl.style.left = `${newLeft}px`;
      this.popupEl.style.top = `${newTop}px`;
    };
    const mouseMoveHandler = (e2) => moveHandler(e2.clientX, e2.clientY);
    const touchMoveHandler = (e2) => {
      if (e2.touches.length > 0) {
        moveHandler(e2.touches[0].clientX, e2.touches[0].clientY);
      }
    };
    const stopDragging = () => {
      isDragging = false;
      if (header)
        header.style.cursor = "grab";
    };
    this.activeHandlers.mousemove = mouseMoveHandler;
    this.activeHandlers.touchmove = touchMoveHandler;
    this.activeHandlers.mouseup = stopDragging;
    this.activeHandlers.touchend = stopDragging;
    document.addEventListener("mousemove", mouseMoveHandler);
    document.addEventListener("mouseup", stopDragging);
    document.addEventListener("touchmove", touchMoveHandler, { passive: false });
    document.addEventListener("touchend", stopDragging);
    const contentArea = this.popupEl.createEl("textarea", { cls: "ai-translator-popup-content" });
    contentArea.style.width = "100%";
    contentArea.style.height = "150px";
    contentArea.style.resize = "vertical";
    contentArea.style.backgroundColor = "var(--background-primary)";
    contentArea.style.color = "var(--text-normal)";
    contentArea.style.border = "1px solid var(--background-modifier-border)";
    contentArea.style.borderRadius = "4px";
    contentArea.style.padding = "8px";
    const fetchResult = async (provider) => {
      var _a;
      contentArea.value = "";
      contentArea.disabled = true;
      const loading = (_a = this.popupEl) == null ? void 0 : _a.createEl("div", { cls: "ai-translator-loading" });
      if (loading) {
        loading.createEl("div", { cls: "ai-translator-spinner" });
        loading.createEl("span", { text: "Analyzing..." });
      }
      try {
        const promptTemplate = this.settings.providerPrompts[provider] || DEFAULT_SETTINGS.providerPrompts[provider];
        const prompt = (promptTemplate == null ? void 0 : promptTemplate.replace("{{targetLanguage}}", this.settings.targetLanguage).replace("{{text}}", text)) || text;
        let result = "";
        switch (provider) {
          case "gemini":
            result = await this.callGemini(prompt);
            break;
          case "openai":
            result = await this.callOpenAI(prompt);
            break;
          case "openrouter":
            result = await this.callOpenRouter(prompt);
            break;
          case "google":
            result = await this.callGoogleTranslate(text);
            break;
          case "free-dictionary":
            result = await this.callFreeDictionary(text);
            break;
        }
        contentArea.value = result;
      } catch (error) {
        contentArea.value = `Error: ${error.message || error}`;
      } finally {
        loading == null ? void 0 : loading.remove();
        contentArea.disabled = false;
      }
    };
    const footer = this.popupEl.createEl("div", { cls: "ai-translator-popup-footer" });
    const dropdownContainer = footer.createEl("div", { cls: "ai-translator-dropdown-container" });
    const select = dropdownContainer.createEl("select", { cls: "ai-translator-popup-select" });
    const allProviders = [
      { id: "gemini", name: "Gemini" },
      { id: "openai", name: "OpenAI" },
      { id: "openrouter", name: "OpenRouter" },
      { id: "google", name: "Google" },
      { id: "free-dictionary", name: "Dict" }
    ];
    allProviders.forEach((p2) => {
      const option = select.createEl("option", { text: p2.name, value: p2.id });
      if (p2.id === this.settings.provider)
        option.selected = true;
    });
    select.onchange = async () => {
      this.settings.provider = select.value;
      await this.saveSettings();
      await fetchResult(select.value);
    };
    this.refreshActivePopup = async (provider) => {
      select.value = provider;
      await fetchResult(provider);
    };
    const saveBtn = footer.createEl("div", { cls: "ai-translator-icon-btn ai-translator-save-btn" });
    (0, import_obsidian.setIcon)(saveBtn, "save");
    (0, import_obsidian.setTooltip)(saveBtn, "Save to Vault");
    saveBtn.onclick = async () => {
      await this.saveDefinition(text, contentArea.value);
    };
    const copyBtn = footer.createEl("div", { cls: "ai-translator-icon-btn" });
    (0, import_obsidian.setIcon)(copyBtn, "copy");
    (0, import_obsidian.setTooltip)(copyBtn, "Copy Content");
    copyBtn.onclick = () => {
      navigator.clipboard.writeText(contentArea.value);
      new import_obsidian.Notice("Copied to clipboard");
    };
    await fetchResult(this.settings.provider);
    this.activeHandlers.escape = (e2) => {
      if (e2.key === "Escape") {
        this.removePopup();
      }
    };
    document.addEventListener("keydown", this.activeHandlers.escape);
    this.activeHandlers.clickOutside = (e2) => {
      if (this.popupEl && !this.popupEl.contains(e2.target) && !isDragging) {
        this.removePopup();
      }
    };
    document.addEventListener("mousedown", this.activeHandlers.clickOutside);
  }
  async saveDefinition(word, definition) {
    try {
      const folderPath = this.settings.saveFolder || "AI-Definitions";
      if (!await this.app.vault.adapter.exists(folderPath)) {
        await this.app.vault.createFolder(folderPath);
      }
      const now = new Date();
      const dateStr = now.toISOString().split("T")[0];
      const timeStr = now.toTimeString().split(" ")[0];
      let extractedAliases = word;
      let cleanedDefinition = definition;
      const aliasMatch = definition.match(/Aliases:\s*(.*)$/m);
      if (aliasMatch) {
        extractedAliases = aliasMatch[1].trim();
        cleanedDefinition = definition.replace(/Aliases:\s*.*$/m, "").trim();
      }
      let saveTemplate = this.settings.useSharedTemplate ? this.settings.sharedSaveTemplate || DEFAULT_SETTINGS.sharedSaveTemplate : this.settings.providerSaveTemplates[this.settings.provider] || DEFAULT_SETTINGS.providerSaveTemplates[this.settings.provider];
      let fileContent = saveTemplate.replace(/{{word}}/g, word).replace(/{{definition}}/g, cleanedDefinition).replace(/{{date}}/g, dateStr).replace(/{{time}}/g, timeStr).replace(/{{aliases}}/g, extractedAliases);
      const fileName = `${word.replace(/[^a-z0-9]/gi, "_").toLowerCase()}.md`;
      const filePath = `${folderPath}/${fileName}`;
      if (await this.app.vault.adapter.exists(filePath)) {
        const timestamp = now.getTime();
        const newPath = `${folderPath}/${word.replace(/[^a-z0-9]/gi, "_").toLowerCase()}_${timestamp}.md`;
        await this.app.vault.create(newPath, fileContent);
        new import_obsidian.Notice(`Saved to ${newPath}`);
      } else {
        await this.app.vault.create(filePath, fileContent);
        new import_obsidian.Notice(`Saved to ${filePath}`);
      }
    } catch (error) {
      console.error("Error saving definition:", error);
      new import_obsidian.Notice(`Error saving: ${error.message}`);
    }
  }
};
var AITranslatorSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Target Language").setDesc("The language you want to translate your text into (e.g., Vietnamese, English, French)").addText((text) => text.setPlaceholder("Vietnamese").setValue(this.plugin.settings.targetLanguage).onChange(async (value) => {
      this.plugin.settings.targetLanguage = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Dictionary Popup Trigger").setDesc("How should the dictionary popup be triggered?").addDropdown((dropdown) => dropdown.addOption("auto", "Automatic (On Selection)").addOption("manual", "Manual (Hotkey Only)").addOption("disabled", "Disabled").setValue(this.plugin.settings.triggerMode).onChange(async (value) => {
      this.plugin.settings.triggerMode = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "AI Provider" });
    new import_obsidian.Setting(containerEl).setName("AI Provider").setDesc("Choose which AI service or Dictionary to use").addDropdown((dropdown) => dropdown.addOption("gemini", "Google Gemini").addOption("openai", "OpenAI").addOption("openrouter", "OpenRouter").addOption("google", "Google Translate").addOption("free-dictionary", "Free Dictionary API").setValue(this.plugin.settings.provider).onChange(async (value) => {
      this.plugin.settings.provider = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    containerEl.createEl("h3", { text: "Provider Loop Configuration" });
    containerEl.createEl("p", { text: 'Select which providers to include when using the "Cycle AI Provider" command.' });
    const providers = [
      { id: "gemini", name: "Google Gemini" },
      { id: "openai", name: "OpenAI" },
      { id: "openrouter", name: "OpenRouter" },
      { id: "google", name: "Google Translate" },
      { id: "free-dictionary", name: "Free Dictionary API" }
    ];
    providers.forEach((p2) => {
      new import_obsidian.Setting(containerEl).setName(p2.name).addToggle((toggle) => toggle.setValue(this.plugin.settings.providerLoop.includes(p2.id)).onChange(async (value) => {
        if (value) {
          if (!this.plugin.settings.providerLoop.includes(p2.id)) {
            this.plugin.settings.providerLoop.push(p2.id);
          }
        } else {
          this.plugin.settings.providerLoop = this.plugin.settings.providerLoop.filter((id) => id !== p2.id);
        }
        await this.plugin.saveSettings();
      }));
    });
    containerEl.createEl("h3", { text: `Settings for ${this.plugin.settings.provider}` });
    const isAIProvider = ["gemini", "openai", "openrouter"].includes(this.plugin.settings.provider);
    if (isAIProvider) {
      new import_obsidian.Setting(containerEl).setName("Custom Prompt").setDesc("Customize how the AI analyzes the selected text. Use {{targetLanguage}} and {{text}} as placeholders.").addTextArea((text) => text.setPlaceholder("Enter your custom prompt here...").setValue(this.plugin.settings.providerPrompts[this.plugin.settings.provider] || "").onChange(async (value) => {
        this.plugin.settings.providerPrompts[this.plugin.settings.provider] = value;
        await this.plugin.saveSettings();
      }));
    }
    new import_obsidian.Setting(containerEl).setName("Save Folder").setDesc("The folder where definitions will be saved.").addText((text) => text.setPlaceholder("AI-Definitions").setValue(this.plugin.settings.saveFolder).onChange(async (value) => {
      this.plugin.settings.saveFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Use Shared Template").setDesc("Use a single template for all providers instead of per-provider templates.").addToggle((toggle) => toggle.setValue(this.plugin.settings.useSharedTemplate).onChange(async (value) => {
      this.plugin.settings.useSharedTemplate = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.useSharedTemplate) {
      new import_obsidian.Setting(containerEl).setName("Shared Save Template").setDesc("The template used for all providers. Placeholders: {{word}}, {{definition}}, {{date}}, {{time}}, {{aliases}}.").addTextArea((text) => text.setPlaceholder("Enter shared template...").setValue(this.plugin.settings.sharedSaveTemplate).onChange(async (value) => {
        this.plugin.settings.sharedSaveTemplate = value;
        await this.plugin.saveSettings();
      }));
    } else {
      new import_obsidian.Setting(containerEl).setName("Save Template").setDesc("The template for the saved definition file. Placeholders: {{word}}, {{definition}}, {{date}}, {{time}}, {{aliases}}.").addTextArea((text) => text.setPlaceholder("Enter template...").setValue(this.plugin.settings.providerSaveTemplates[this.plugin.settings.provider] || "").onChange(async (value) => {
        this.plugin.settings.providerSaveTemplates[this.plugin.settings.provider] = value;
        await this.plugin.saveSettings();
      }));
    }
    containerEl.createEl("h3", { text: "Provider Settings" });
    if (this.plugin.settings.provider === "gemini") {
      new import_obsidian.Setting(containerEl).setName("Gemini API Key").setDesc("Your Google Gemini API Key").addText((text) => {
        text.inputEl.type = "password";
        text.setPlaceholder("Enter your API key").setValue(this.plugin.settings.geminiApiKey).onChange(async (value) => {
          this.plugin.settings.geminiApiKey = value;
          await this.plugin.saveSettings();
        });
      });
      new import_obsidian.Setting(containerEl).setName("Gemini Model").setDesc("Which model to use (e.g., gemini-1.5-pro, gemini-1.5-flash)").addText((text) => text.setPlaceholder("gemini-1.5-pro").setValue(this.plugin.settings.geminiModel).onChange(async (value) => {
        this.plugin.settings.geminiModel = value;
        await this.plugin.saveSettings();
      }));
    } else if (this.plugin.settings.provider === "openai") {
      new import_obsidian.Setting(containerEl).setName("OpenAI API Key").setDesc("Your OpenAI API Key").addText((text) => {
        text.inputEl.type = "password";
        text.setPlaceholder("Enter your API key").setValue(this.plugin.settings.openaiApiKey).onChange(async (value) => {
          this.plugin.settings.openaiApiKey = value;
          await this.plugin.saveSettings();
        });
      });
      new import_obsidian.Setting(containerEl).setName("OpenAI Model").setDesc("Which model to use (e.g., gpt-4o, gpt-4-turbo, gpt-3.5-turbo)").addText((text) => text.setPlaceholder("gpt-4o").setValue(this.plugin.settings.openaiModel).onChange(async (value) => {
        this.plugin.settings.openaiModel = value;
        await this.plugin.saveSettings();
      }));
    } else if (this.plugin.settings.provider === "openrouter") {
      new import_obsidian.Setting(containerEl).setName("OpenRouter API Key").setDesc("Your OpenRouter API Key").addText((text) => {
        text.inputEl.type = "password";
        text.setPlaceholder("Enter your API key").setValue(this.plugin.settings.openRouterApiKey).onChange(async (value) => {
          this.plugin.settings.openRouterApiKey = value;
          await this.plugin.saveSettings();
        });
      });
      new import_obsidian.Setting(containerEl).setName("OpenRouter Model").setDesc("Which model to use (e.g., meta-llama/llama-3-8b-instruct, anthropic/claude-3-haiku)").addText((text) => text.setPlaceholder("meta-llama/llama-3-8b-instruct").setValue(this.plugin.settings.openRouterModel).onChange(async (value) => {
        this.plugin.settings.openRouterModel = value;
        await this.plugin.saveSettings();
      }));
    }
  }
};
